version: "3.9"

services:

  backend:

    build: .

    container_name: snaptask-backend

    ports:
      - "8000:8000"

    volumes:
      - .:/app

    env_file:
      - .env

    depends_on:
      - postgres

    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload

  postgres:

    image: postgres:17

    container_name: snaptask-db

    restart: always

    environment:

      POSTGRES_USER: postgres

      POSTGRES_PASSWORD: postgres

      POSTGRES_DB: snaptask

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:

  postgres_data: